# Generated by Django 5.1.6 on 2025-02-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scopes_tag_scopes_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scopes',
            new_name='Scope',
        ),
    ]
